### ISSUE TITLE
Limited by numerical precision

### ISSUE THREAD

**Issue by scasplte2** [stggh/PyDiatomic#3]
Dr. Gibson,

First off, thanks so much for sharing your work on Github. I am a phd student working in ultracold AMO physics and I have been using your package to calculate bound state wavefunctions for strontium dimers. The states we are interested in are halo states, where the wavefunction extends well into the classically forbidden regime as shown below
![image](https://user-images.githubusercontent.com/1753335/55284865-a6a19680-5344-11e9-9de6-01fdc8d1e359.png)

As this state is only bound by ~80 kHz (approx 1e-10 eV) I had a little trouble getting the solution to converge at first but was able to find solutions by increasing the scaling factor on line 300 of johnson.py from 1e3 to 1e6. But now I am having an issue where I am attempting to slightly tweak the potential (via the C6 parameter) and see if this can move the bound state binding energy. Unfortunately, I keep converging to the same solution when I make minor tweaks to the potential. Large tweaks result in a new solution but these are much too large for the effect I am looking for (trying to move the binding energy by ~13 kHz).

I am hoping you can point me where to look or what may be causing the same solution to appear with different potentials. Please let me know if I can provide any further information.

**Comment by stggh** [comment]
@scasplte2 thank you for making use of `PyDiatomic`, and for creating this issue.

Are you using the latest version, `matching_point` branch?

  `git clone https://github.com/stggh/PyDiatomic.git -b matching_point`

I am very interested in tracking down this bug.

I had previously found a problem with `scipy.optimize.least-squares` persistently  hunting to the lower eigenvalue. In the `matching_point` branch I could not locate the `1e3` factor, so please try the new code. If you are able to share your potential curve, to help the debugging, that would be great.

I would also welcome any feedback to improve the user API.

I am currently travelling, but should be able to examine this problem.

**Comment by stggh** [comment]
I think the `matching_point` version does not have the eigenvalue issue. 

Here is a Morse potential curve test case, that tweaks the `beta` parameter to give a 13 kHz eigenvalue shift:
```python
import numpy as np
import cse
import matplotlib.pyplot as plt
import scipy.constants as C

a0 = C.physical_constants['Bohr radius'][0]*1e10
ev2cm = C.e/(C.h*C.c*100)
cm2kHz = C.c/10

r = np.arange(3, 1e4, 0.01)

beta = 0.91
M = cse.tools.analytical.Morse(r, 4.6685, 1130.84, 19, beta)
betam = 0.909999995
Mm = cse.tools.analytical.Morse(r, 4.6685, 1130.84, 19, betam)

X = cse.Cse('Sr2', VT=[(r, M)])
Xm = cse.Cse('Sr2', VT=[(r, Mm)])

De = X.VT[0, 0][-1]*8065.541
Dem = Xm.VT[0, 0][-1]*8065.541

Xm.solve(De-1)
X.solve(Dem-1)

print(f'EXm{Xm.vib:2d} = {Xm.cm*cm2kHz:8.5f}')
print(f'EX{X.vib:2d} = {X.cm*cm2kHz:8.5f}')
print(f'EX{X.vib:2d}-EXm{Xm.vib:2d} = {(X.cm-Xm.cm)*cm2kHz:8.5f}')

plt.plot(Xm.R/a0, (Xm.wavefunction.T[0, 0]/2+Xm.cm-Dem)*cm2kHz,
             label=r'$\beta=$'+f'{betam:.9f}')
plt.plot(X.R/a0, (X.wavefunction.T[0, 0]/2+X.cm-De)*cm2kHz,
             label=r'$\beta=$'+f'{beta:.9f}')

plt.plot(Xm.R/a0, (Xm.VT[0,0]*ev2cm-Dem)*cm2kHz, label='Xm')
plt.plot(Xm.R/a0, (X.VT[0,0]*ev2cm-De)*cm2kHz, label='X')

plt.legend(fontsize='small', labelspacing=0.1)
plt.xscale('log')
plt.xlim([5, 1e4])
plt.ylim([-7e7, 1e7])

plt.savefig('13kHz.png', dpi=100)
plt.show()
```

```
python Sr2perturb.py
EXm57 = 34426340285.69486
EX57 = 34426340298.77347
EX57-EXm57 = 13.07860
```
![13kHz](https://user-images.githubusercontent.com/10932229/56112208-ac7eb500-5f9d-11e9-8657-27dac51d4ab4.png)


Takes a while to execute.

**Comment by stggh** [comment]
Closed, as I believe the current version, with a more reliable eigenvalue hunting algorithm, fixes this issue?
