### ISSUE TITLE
Which partial cross section did Pydiatomic give us?

### ISSUE THREAD

**Issue by ghost** [stggh/PyDiatomic#8]
Dear Prof. Stephen Gibson

You did a very very nice work.

I meet some trouble in using Pydiatomic. 

I try to simplify the problem and verify direct photodissociation. I try to test and repeat the BeH+ photodissociation $X^1\Sigma^+$ - $C^1\Sigma^+$ [J. Quant. Spectrosc. Radiat. Transfer 254, 107203 (2020)]. I run the following code, and get the bad results:

```python 
import numpy as np
import cse
import matplotlib.pyplot as plt

X = cse.Cse('BeH', VT=['potentials/BeH-X.dat'], en=800)
C = cse.Cse('BeH', VT=['potentials/BeH-C.dat'])
CX = cse.Transition(C, X, 
                dipolemoment=['transitionmoments/BeH-TDM-X-C.dat'],
                transition_energy=np.arange(55000, 90000, 100)) 

plt.plot(CX.wavenumber, CX.xs*1.0e16)

np.savetxt('out.txt', np.array([CX.wavenumber,CX.xs[:, 0]]).transpose())

plt.xlabel("Wavenumber (cm$^{-1}$)")
plt.ylabel("Cross section ($10^{-16}$ cm$^{2}$)")
plt.title("BeH$^{+}$ $X^{3}\Sigma^{+}$ - $B^{1}\Pi$")
plt.savefig("test.png", dpi=75)
```

Results of [JQSRT 254, 107203 (2020)] are in file Compare.txt.  The photodissociaton crosssection is from $X^1\Sigma^+$ (v=0, j=0) and final state $C^1\Sigma^+$ (j=1). Compare.txt is different from the Pydiatomic results.

My question :  which partial cross section did Pydiatomic give? 

P.S.  My test file can download in [this link](http://ykphy.top/wp-content/uploads/2021/05/20210507BeH.zip).

**Comment by stggh** [comment]
Thanks for supplying all the detail, and your working files.

The main issue is with your input data:
1) For the potential curves of Yang <i>et al.</i> the conversion factor of atomic units to Angstr&ouml;m is <math>x0.529177</math>, which places <i><math>R<sub>e</sub></math></i> around  1.3&#8491;.  You may have divided by that factor.
2) The `en=###` parameter in `cse.Cse()` is an initial guess for the particular eigenvalue. This should be ~1100 cm<sup>-1</sup>, although 800 (the O<sub>2</sub> value) does in fact work.
3) The <math>C-X</math> transition moment has a maximum value ~1 a.u.
4) Transition energies need to be above the <math>X-</math> state dissociation energy, to evaluate a cross section (i.e. there should be at least one open channel).  

I have re-scaled your input curves with the scripts `potentials/convert.py` and `transitionmoments/convert.py`. 

First, we may examine the <math>X-</math>state:
```python
[Gibbo:.+ython/BeH/ykphy]$ ipython
Python 3.8.6 (default, Jan 27 2021, 15:42:20) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import cse

In [2]: X = cse.Cse('BeH', VT=['potentials/BeHx-X.dat'])

In [3]: X.levels(10)
X

In [4]: X
Out[4]: 

Molecule: BeH  mass: 1.50521e-27 kg, 0.906457 amu
Electronic state: potentials/BeHx-X.dat
eigenvalues (that have been evaluated for this state):
 v  rot   energy(cm-1)    Bv(cm-1)     Dv(cm-1)
 0   0     1089.841      10.65596      1.031e-03
 1   0     3220.404      10.33747      1.023e-03
 2   0     5434.846       9.89444      1.682e-03
 3   0     7284.296       9.65817      1.205e-03
 4   0    10105.549       8.29409      2.676e-02
 5   0    11383.098       8.48179      4.705e-03
 6   0    12775.761       8.48167      2.135e-03
 7   0    14397.282       8.08323      2.371e-03
 8   0    16204.887       7.34494      5.893e-03
 9   0    16704.887       7.31939     -6.389e-03
10   0    18616.676       7.07644      1.593e-03
11   0    19116.676       6.17849     -1.605e-02
20   0    25446.279       0.73252      6.726e-03
```

The values <math>v"=11, 20</math> arise from the interpolation of energy levels. <math>X<sub>v"=0</sub></math> has the eigenvalue 1089.8 cm<sup>-1</sup> which is in the ball park, as is the rotational constant.

Running a modified version of your `test.py` gives:

![image](https://user-images.githubusercontent.com/10932229/117521286-5a7bb280-aff0-11eb-8ab3-debfd7569a13.png)

This calculation "looks" like the experimental data of Yang <i>et al.</i> Fig. 3.  I am not sure what their Fig. 2 represents, perhaps they plotted the data wrong (backwards)?  The calculation is intuitively correct, in that the overlap integral is expected to increase as more of the <math>C-</math>state continuum-wavefunction overlaps with the ground state wavefunction. 

Here is the code:
1) `potentials/convert.py`
```python
 import numpy as np
from scipy.interpolate import splrep, splev

rX, vX = np.loadtxt('BeH-X.dat', unpack=True)
rC, vC = np.loadtxt('BeH-C.dat', unpack=True)

rX *= 0.529177**2
rC *= 0.529177**2

splX = splrep(rX, vX)
splC = splrep(rC, vC)

rmin = max(rX[0], rC[0])
rmax = min(rX[-1], rC[-1])
Rmin = int(rmin*1000)/1000
Rmax = int(rmax*1000)/1000
print(Rmin, Rmax)

Rmin = 0.8
Rmax = 10.8

R = np.arange(Rmin, Rmax, 0.01)
np.savetxt('BeHx-X.dat', np.column_stack((R, splev(R, splX))),
           fmt='%8.3f %10.5e')
np.savetxt('BeHx-C.dat', np.column_stack((R, splev(R, splC))),
           fmt='%8.3f %10.5e')
```
Note, the potential curve files are now `BeHx...`

2) `transitionmoments/convert.py`
  ```python
import numpy as np
from scipy.interpolate import splev, splrep

rT, dT = np.loadtxt('BeH-TDM-X-C.dat', unpack=True)

rT *= 0.529177**2
dT /= dT.max()

R = np.arange(0.8, 10.8, 0.01)

splT = splrep(rT, dT)

np.savetxt('BeHx-TDM-X-C.dat', np.column_stack((R, splev(R, splT))),
           fmt='%8.5f %8.5f')
```

3) `BeH+.py`   = your `test.py`
  ```python
import numpy as np
import cse
import matplotlib.pyplot as plt

X = cse.Cse('BeH', VT=['potentials/BeHx-X.dat'], en=1100)
C = cse.Cse('BeH', VT=['potentials/BeHx-C.dat'])
CX = cse.Transition(C, X,
                dipolemoment=['transitionmoments/BeHx-TDM-X-C.dat'],
                transition_energy=np.arange(62000, 150000, 10.0))


np.savetxt('BeH+.txt', np.array([CX.wavenumber, CX.xs[:, 0]]).transpose())

# plot ---------
fig, (ax0, ax1) = plt.subplots(1, 2, tight_layout=True)

au = 0.529177
eh = 27.211386
offset = X.VT[0, 0][-1]/eh
ax0.plot(X.R/au, X.VT[0, 0]/eh-offset, label=r'$X ^{1}\Sigma^+$')
ax0.plot(C.R/au, C.VT[0, 0]/eh-offset, label=r'$C ^{1}\Sigma^+$')
ax0.axis(xmin=0, xmax=20, ymin=-0.2, ymax=0.6)
ax0.set_xlabel('R (a.u.)')
ax0.set_ylabel('Potential enevery (a.u.)')
ax0.legend(labelspacing=0.1, fontsize='small')

ax1.semilogy(1e7/CX.wavenumber, CX.xs*1e18)
ax1.set_xlabel("Wavelength (nm)")
ax1.set_ylabel(r"Cross section ($10^{-18}$ cm$^{2}$)")
# ax1.title(r"BeH$^{+}$ $C ^{1}\Sigma^{+} - X^{1}\Sigma^{+}$")
ax1.axis(ymin=1e-9, ymax=1e3)

plt.savefig("BeH+.png", dpi=75)

plt.show()
```

Code listed above, as for some reason I could not generate a `gist` by dragging files on my desktop.


I hope this helps.
